
on:
  # push:
  #   branches: [ main, dev ]
  pull_request:
    branches: [ main ]

name: Trivy code scan

permissions:
  id-token: write # for writing security events.
  security-events: write
  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  trivy_scan_code:
    name: Trivy code scan - dev
    environment: vuonghuynh-poc_dev
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Code scan with Trivy 
        uses: aquasecurity/trivy-action@0.30.0
        with: 
          scan-type: 'fs'
          scan-ref: '.' 
          format: 'sarif'
          ignore-unfixed: true
          scanners: 'vuln,secret,misconfig'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          output: 'trivy-code-results.sarif'

      - name: Upload Trivy code scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-code-results.sarif'
          category: 'Trivy Code Scan'
          wait-for-processing: true

